version: "3"
services:
  feathers:
    build: .
    command: npm run dev
    depends_on:
      - mongodb
    ports:
      - 3030:3030
    volumes:
      - ./data:/app/data
      - ./src:/app/src
      - ./public:/app/public
      - ./config:/app/config
      - ./test:/app/test
    environment:
      - NODE_ENV=docker
  mongodb:
    image: mongo:3.6.7
    ports:
      - 27017:27017
    volumes:
       - mongodb-data:/data/db

volumes:
  mongodb-data:
